Human readable uid
hpi-swa-teaching/CollaborativeCodeEditing pull request #7
Opened 2019-05-29 19:36 UTC by ADimeo

This branch implements a UI window which allows users to set their name for collaboration.

It does not deal with anything network related, and does not have full test coverage, see #6 for details regarding that.

2019-05-30 18:21 UTC, arminWel commented
I know, that there may not be foll test coverage due to #6. Nevertheless all test, which are already implemented should work in a PR. Is there a specific reason for them not to in this case?

2019-06-01 17:00 UTC, arminWel requested changes

2019-06-01 17:00 UTC, arminWel commented on packages/CollabCodeEdit-Client.package/CCEAccount.class/class/default.st
> +as yet unclassified
Always classify methods.

2019-06-01 17:00 UTC, arminWel commented on packages/CollabCodeEdit-Client.package/CCEAccount.class/class/reset.st
> +as yet unclassified
Always classify methods.

2019-06-01 17:00 UTC, arminWel commented on packages/CollabCodeEdit-Client.package/CCEAccount.class/instance/humanReadableName.st
> +	^humanReadableName ifNil: [
```suggestion
	^ humanReadableName ifNil: [ 
```

2019-06-01 17:00 UTC, arminWel commented on packages/CollabCodeEdit-Tests.package/CCEAcccountTests.class/instance/setUp.st
> +as yet unclassified
Always classify methods.

2019-06-01 17:00 UTC, arminWel commented on packages/CollabCodeEdit-Tests.package/CCEAcccountTests.class/instance/testChangeHumanReadableName.st
> +as yet unclassified
Always classify methods.

2019-06-01 17:00 UTC, arminWel commented on packages/CollabCodeEdit-Tests.package/CCEAcccountTests.class/instance/testChangeHumanReadableName.st
> +	| everChangingName |
```suggestion
	| everChangingName |
	
```

2019-06-01 17:00 UTC, arminWel commented on packages/CollabCodeEdit-Tests.package/CCEAcccountTests.class/instance/testHumanReadableNameDefaultsToAuthorInitials.st
> +as yet unclassified
Always classify methods.

2019-06-01 17:00 UTC, arminWel commented on packages/CollabCodeEdit-Tests.package/CCEModelTests.class/instance/testBuildGlobalStateAccountDisplayWithCCEAccountAsModel.st
> +
```suggestion
```

2019-06-01 17:00 UTC, arminWel commented on packages/CollabCodeEdit-Tests.package/CCEModelTests.class/instance/testBuildGlobalStateDisplayReturnsCollection.st
> +	self assert: (spec isKindOf: Collection).
```suggestion
	self assert: (spec isKindOf: Collection)
```
Delete the trailing whitespace

2019-06-02 12:38 UTC, simonstadlinger requested changes

2019-06-02 12:38 UTC, simonstadlinger commented on packages/CollabCodeEdit-Client.package/CCEModel.class/instance/buildGlobalStateAccountDisplayWith..st
> +		model: CCEAccount default;
I would suggest to handle this as all our other singletons: create a instance variable in CCEModel and use this one for all usages of this singleton.
```suggestion
		model: self account;
```

2019-06-02 12:38 UTC, simonstadlinger commented on packages/CollabCodeEdit-Client.package/CCEModel.class/instance/buildGlobalStateAccountDisplayWith..st
> +		model: CCEAccount default;
I know, in the existing code base at your state, this is not how we deal with singletons. in SessionManagment we do.

2019-06-02 17:44 UTC, simonstadlinger approved these changes
well done!

2019-06-02 17:45 UTC, simonstadlinger approved these changes

2019-06-05 10:11 UTC, merged