Fix broken call of sourceCode
hpi-swa-teaching/CollaborativeCodeEditing pull request #8
Opened 2019-05-31 13:25 UTC by ADimeo

This fixes a broken (on my system) method call.

The method CompiledMethod sourceCode does not exist on my system. CompiledMethod getSource does, however. I do not know how the former call ended up in our image, since none of the SWE-images include this call.

2019-06-01 16:42 UTC, arminWel commented
The method `#getSource:` is not implemented(at least not in my image), while `#sourceCode:` is. Therefore is must recline this PR.  Reasons for the differences in the images should be discussed with the chair as soon as possible(maybe monday morning? @ADimeo).

2019-06-02 19:25 UTC, arminWel commented
For some reason (those must be quite weird), my Image know has the method the way you have. We should definitely ask at the chair about that-

2019-06-03 11:37 UTC, arminWel approved these changes

2019-06-04 08:11 UTC, arminWel commented
There are problems with older versions of squeak. Thus have to be solved, before we merge. I'm working on it.

2019-06-05 08:16 UTC, PaulBrachmann requested changes
Looks great. It is indeed quite the relief to finally see a build passing!

There are however some minor style inconsistencies that should be fixed.
For further information, refer to our [Smalltalk Style Guide](https://docs.google.com/document/d/11PfOTymUnovjca5ExAI6-6-cC16f6q5mQ8juo9Wn13I/edit?usp=sharing).

2019-06-05 08:16 UTC, PaulBrachmann commented on packages/CollabCodeEdit-Tests.package/CCEModelTest.class/instance/tearDown.st
> +	self newMorphs do: [:morph | morph model changed: #close].
```suggestion
	self newMorphs do: [ :morph | morph model changed: #close ].
```

2019-06-05 08:16 UTC, PaulBrachmann commented on packages/CollabCodeEdit-Tests.package/CCEPackageManagerTests.class/instance/testHashchangesAfterMetaClassInformationChange.st
> +	[ hashBeforeChange := packageManager hashPackages: #( 'CollabCodeEdit-Tests' ).
Code following a multiline block being opened should be indented. (See lines below.)

2019-06-05 08:16 UTC, PaulBrachmann commented on packages/CollabCodeEdit-Tests.package/CCEPackageManagerTests.class/instance/testHashchangesAfterMetaClassInformationChange.st
> +	ensure: [testClass comment: originalComment]
```suggestion
	ensure: [ testClass comment: originalComment ]
```

2019-06-05 08:16 UTC, PaulBrachmann commented on packages/CollabCodeEdit-Tests.package/CCEPackageManagerTests.class/instance/testHashchangesAfterMetaClassInformationChange.st
> +	ensure: [testClass comment: originalComment]
The current indentation makes it unclear that `ensure:` belongs to the preceding block.

2019-06-05 08:16 UTC, PaulBrachmann commented on packages/CollabCodeEdit-Tests.package/CCEPackageManagerTests.class/instance/testHashchangesAfterMetaClassInformationChange.st
> +	self deny: hashBeforeChange = hashAfterChange. ]
```suggestion
	self deny: hashBeforeChange = hashAfterChange ]
```

2019-06-05 09:23 UTC, merged